### PR TITLE
Differentiate login/reg with alternating colors

### PR DESCRIPTION
**Pull request by jaytran505**
created two separate style sheets with colors for login and register. Which one is used changes depends on the operation
IMG_7625
IMG_7624

### CODE REVIEW

**Review by rsquared226 — CHANGES_REQUESTED** [review]
John and I worked together for this one and the only thing is that on Android the mountains appear over the buttons and become unclickable even if we set individual components' `zIndex`s to 2 (mountains having a zIndex of 1)

I'm prob gonna fix this since this looks like an Android only problem, I'm thinking of making the background semi-transparent so we don't have to mess with zIndexes at all. I'll see though, hopefully by the end of today.
@mbullington if you have any idea of a potential fix lmk

Screenshot_20201013-144551

**Comment by mbullington** [comment]
Looks looks awesome! And minimal changes

For the mountains, I feel there's the larger problem of the inputs not properly avoiding the keyboard

What I'd recommend trying:
- Could we have the mountains instead of being `absolute`, being normal positioning but with `justifySelf: 'flex-end'`? Not 100% sure if this would work but it would add it to the box model preventing the overlap.
- Wrapping the primary container in a [KeyboardAvoidingView](https://reactnative.dev/docs/keyboardavoidingview) so it scrolls properly when the keyboard is up

**Review by mbullington — CHANGES_REQUESTED** [review]
oops already wrote this in a comment

**Review by rsquared226 — APPROVED** [review]
Got it working on Android by simply wrapping the View of the Mountain and ScrollView in another View that only has a background color so we wouldn't have to deal with more complicated stuff. The diff for the commit looks like it has a lot more than that but that's only because of indentation

@jaytran505 @mbullington can you confirm that it still works perfectly on iOS just in case?

**Pull request merged**
