### PR TITLE
Jon/next event card

### PR DESCRIPTION
**Pull request by jaytran505**
I added the next event onto the home page with its own title. I'm considering changing the font/font colors of the next event card to better match the cards on the home page so let me know what you think about that.
IMG_7657

### CODE REVIEW

**Comment by rsquared226** [comment]
This is pretty pog, the bottom margin for "next event" is only slightly off on android but other than that it looks great. I think one thing we gotta make sure of is that the next event is actually the next event, we can sort it and stuff if we wanna make sure

How it looks on Android:
Screenshot_20201024-184422

I was thinking the "next event" text would be more like this, like low-key:
image

**Comment by mbullington** [comment]
Great first PR!!

Looks good, I had a few suggestions though:

- Can the next event be at the top? I feel this is the most relevant information
- Can the subtitle look more like this? Feel the subtitle is too bold similar to @rsquared226 
![Uploading 97096779...]

**Comment by jaytran505** [comment]
Moved the card to the top, changed the font, font size, and color of the subtitle to be more lowkey.
IMG_7685

**Review by rsquared226 — APPROVED** [review]
yote

**Pull request merged**
