### PR TITLE
Beautify login

### PR DESCRIPTION
**Pull request by rsquared226**
Everything's functional except for the "forgot password" button

### CODE REVIEW

**Comment by rsquared226** [comment]
I made the changes for 1 and 3, but the pending dialog still stays a little after it's done loading and I don't know if there's a way to fix that because it should go away right after isPending turns false. Maybe it's the animation? Do you think it's too big of a deal if we can't fix it? I linked a gif to how it looks below.

I'll work on the first part of 2 if I have more time later today, but I don't understand the "having it alternate between Sign In and Register" part. Are you saying the title would be Sign in or Register depending on the operation?

ScreenRec_20191231_122419

**Comment by mbullington** [comment]
I don't think that's a huge deal, no problem.

And yeah, I think very similar to the HOME and EVENTS subtitles, except "Sign In" or "Register" depending on the operation.

**Comment by rsquared226** [comment]
Would something like this be better?

image

**Comment by mbullington** [comment]
That looks great! However, if you'd like to keep it white, that's completely up to you.

That's totally what I was talking about in regards to the LOGIN header though.

**Comment by rsquared226** [comment]
Sweet I'll work on it! I changed it to the white theme and I think they both look good, lmk which one you like better.

image

**Comment by mbullington** [comment]
I think white may be better since it contrasts more with the main screen of the app.

Good work!

**Pull request merged**
